local STRINGS = GLOBAL.STRINGS

STRINGS.GF = {}
STRINGS.GF.SPELLS = {}
STRINGS.GF.SPELLS.INVALID_TITLE = "<NONE>"

STRINGS.GF.SPELLS.EQUIP_CRUSHLIGHTNING = {}
STRINGS.GF.SPELLS.EQUIP_CRUSHLIGHTNING.TITLE = "Crushing Lightning"

STRINGS.GF.SPELLS.EQUIP_CHAINLIGHTNING = {}
STRINGS.GF.SPELLS.EQUIP_CHAINLIGHTNING.TITLE = "Chain Lightning"

STRINGS.GF.SPELLS.EQUIP_GROUND_SLAM = {}
STRINGS.GF.SPELLS.EQUIP_GROUND_SLAM.TITLE = "Ground Slam"

STRINGS.GF.SPELLS.AMULET_MAGIC_ECHO = {}
STRINGS.GF.SPELLS.AMULET_MAGIC_ECHO.TITLE = "Magic Echo"