local STRINGS = GLOBAL.STRINGS

STRINGS.GF = {}
STRINGS.GF.SPELLS = {}
STRINGS.GF.SPELLS.INVALID_TITLE = "<NONE>"

STRINGS.GF.SPELLS.EQUIP_CRUSHLIGHTNING = {}
STRINGS.GF.SPELLS.EQUIP_CRUSHLIGHTNING.TITLE = "Crushing Lightning"

STRINGS.GF.SPELLS.EQUIP_CHAINLIGHTNING = {}
STRINGS.GF.SPELLS.EQUIP_CHAINLIGHTNING.TITLE = "Chain Lightning"

STRINGS.GF.SPELLS.EQUIP_GROUND_SLAM = {}
STRINGS.GF.SPELLS.EQUIP_GROUND_SLAM.TITLE = "Ground Slam"

STRINGS.GF.SPELLS.AMULET_MAGIC_ECHO = {}
STRINGS.GF.SPELLS.AMULET_MAGIC_ECHO.TITLE = "Magic Echo"

STRINGS.NAMES.GF_LIGHTNING_SPEAR = "Electro-spear"
STRINGS.RECIPE_DESC.GF_LIGHTNING_SPEAR = "Electro-spear."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GF_LIGHTNING_SPEAR = "The electric power."

STRINGS.NAMES.GF_TENTACLE_STAFF = "Tentacle staff"
STRINGS.RECIPE_DESC.GF_TENTACLE_STAFF = "Tentacle staff."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GF_TENTACLE_STAFF = "Brrrr..."

STRINGS.NAMES.GF_MAGIC_ECHO_AMULET = "Amulet of doubling"
STRINGS.RECIPE_DESC.GF_MAGIC_ECHO_AMULET = "Amulet of doubling."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GF_MAGIC_ECHO_AMULET = "Twice more magic!"

